name: CI

on: push

jobs: 
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get current display mode
        run: ./displayMode

      - name: run snapshot tests
        run: swift test
        env:
          SNAPSHOT_ARTIFACTS: "./.temp/artifacts"

      - name: Archive failing snapshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: failing-snapshots
          path: .temp/artifacts/MacSnapshottestingTests/*.png